package com.zolad.filterrenderer.filter.blend;

import android.opengl.GLES20;

public class BlendParam {

    public static String[] paramStr=new String[]{
            "GL_ZERO","GL_ONE","GL_SRC_COLOR","GL_ONE_MINUS_SRC_COLOR",
            "GL_DST_COLOR","GL_ONE_MINUS_DST_COLOR","GL_SRC_ALPHA","GL_ONE_MINUS_SRC_ALPHA",
            "GL_DST_ALPHA","GL_ONE_MINUS_DST_ALPHA","GL_CONSTANT_COLOR","GL_ONE_MINUS_CONSTANT_COLOR",
            "GL_CONSTANT_ALPHA","GL_ONE_MINUS_CONSTANT_ALPHA","GL_SRC_ALPHA_SATURATE"
    };

    public static int[] paramInt=new int[]{
            GLES20.GL_ZERO,GLES20.GL_ONE,GLES20.GL_SRC_COLOR,GLES20.GL_ONE_MINUS_SRC_COLOR,
            GLES20.GL_DST_COLOR,GLES20.GL_ONE_MINUS_DST_COLOR,GLES20.GL_SRC_ALPHA,GLES20.GL_ONE_MINUS_SRC_ALPHA,
            GLES20.GL_DST_ALPHA,GLES20.GL_ONE_MINUS_DST_ALPHA,GLES20.GL_CONSTANT_COLOR,GLES20.GL_ONE_MINUS_CONSTANT_COLOR,
            GLES20.GL_CONSTANT_ALPHA,GLES20.GL_ONE_MINUS_CONSTANT_ALPHA,GLES20.GL_SRC_ALPHA_SATURATE
    };

    public static int[] equaInt=new int[]{
            GLES20.GL_FUNC_ADD,GLES20.GL_FUNC_SUBTRACT,GLES20.GL_FUNC_REVERSE_SUBTRACT
    };
}
